### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by seagle0128** [purcell/ibuffer-projectile#11]
If I enable `ibuffer-projectile` , the emacs is getting slow. Here is the profiler data.

```elisp
(use-package ibuffer-projectile
  :bind ("C-x C-b" . ibuffer)
  :hook ((ibuffer . ibuffer-auto-mode)
         (ibuffer . ibuffer-projectile-set-filter-groups)
         (ibuffer . (lambda ()
                      (unless (eq ibuffer-sorting-mode 'alphabetic)
                        (ibuffer-do-sort-by-alphabetic)))))
  :config (setq ibuffer-filter-group-name-face 'font-lock-function-name-face))
```

![image](https://user-images.githubusercontent.com/140797/48932099-f276a600-ef34-11e8-891e-0adb8e35ca35.png)

**Comment by purcell** [comment]
Hmmm. I guess calling `projectile-project-root` for each of the buffers is expensive because that function is not caching results efficiently for some reason, though the code indicates that it tries to.

Personally I use `ibuffer-vc`, and not this package.

**Comment by seagle0128** [comment]
I guess so. I disable `ibuffer-auto-mode` and seems better.

**Comment by purcell** [comment]
Ah yes, I can imagine that would be quite inefficient when grouping buffers non-trivially.

**Comment by seagle0128** [comment]
I am closing this issue since it works well after disabling `ibuffer-auto-mode`. Thanks!

**Comment by Atemu** [comment]
In my case, disabling ibuffer-auto-mode does not fix the issue. Spacemacs uses this package for ibuffer grouping by default, so this should affect quite a few users.

I can see @fuyu0425 created a projectile patch that supposedly lessens the impact of this issue. Did that ever get upstreamed?

**Comment by fuyu0425** [comment]
Ah no, I don't send a pull request.
Because at my computer, a lot of `file-truename` really takes a long time, maybe due to the macOS or the endpoint management software that hook any system calls.

The patch is a little hacky, though.
