### ISSUE TITLE
ibuffer for each projectile project

### ISSUE THREAD

**Issue by mcraveiro** [purcell/ibuffer-projectile#14]
Hi ibuffer-projectile developers,

thanks very much for a really useful mode. I have a question, which may actually be a feature request - not too sure. I installed ibuffer-projectile, but it seems that I can either use it with its per-project filter groups, or I can keep my existing filter groups [1], but not have both. I guess this is a side-effect of the fact that you do not seem to be able to have nested filter groups in ibuffer (i.e. group first by project and then by user defined filter group).

Failing some form of nesting, I guess what I really would like to have is my regular "global ibuffer", with all the open buffers, and then a second "local ibuffer", bound to a separate key and with exactly the same filter groups, but with two differences:

- only see buffers for the current active projectile project
- all paths to be relative to the projectile project root instead of full paths.

Is this possible to do with ibuffer-projectile?

Many thanks for your time.

[1] https://github.com/mcraveiro/prelude/blob/personal/personal/init-ibuffer.el

**Comment by mcraveiro** [comment]
Hi ibuffer-projectile developers,

let me know if this is something you are not interested in and I can close the ticket.

Cheers

Marco

**Comment by purcell** [comment]
I don't think that's something supported by `ibuffer`, and `ibuffer-projectile` is just a way to make filter groups that `ibuffer` can use. So nested groups would be more of an `ibuffer` feature request. As for having "global" and "local" ibuffer views, this is something you could implement with a few functions, I expect, by setting the various ibuffer view variables appropriately in the local ibuffer.

**Comment by mcraveiro** [comment]
Thanks, makes sense.

**Comment by mcraveiro** [comment]
Aha, thanks to your tip, I figured out how to achieve what I wanted! Apparently there is a ```ibuffer-filter-by-directory``` [1] which can take a path to a project and shows buffers for files on that directory only! The filter groups are unaffected. Shame I need to enter the directory manually, but other than that its perfect! :-)

[1] https://stackoverflow.com/questions/50149328/filter-file-visiting-buffers-in-emacs-ibuffer

**Comment by purcell** [comment]
Nice, glad you figured it out.

**Comment by mcraveiro** [comment]
OK for anyone finding this in the future, I have no idea how I missed this but projectile already implements the functionality I required; its ```projectile-ibuffer```:

https://github.com/bbatsov/projectile/blob/master/projectile.el#L4279

It seems to come out of the box as of the writing of this comment. This keeps all your filters exactly as they are, but only displays buffers for the current project. You can also use it side by side with a "global" ibuffer.

**Comment by purcell** [comment]
> projectile already implements the functionality I required; its `projectile-ibuffer`

Wow, you're right - it looks like the built-in support for `ibuffer` landed in Projectile 6 months before I wrote this by adapting `ibuffer-vc` (which is what I use myself).
