### ISSUE TITLE
Hide Helm buffers

### ISSUE THREAD

**Issue by manuel-uberti** [purcell/ibuffer-projectile#3]
Hi,

first of all, thanks for this package.

I'd like to know whether it is possible to filter out Helm buffers, such as `*helm recentf*`. 
Actually all the ones starting with `*helm` are of no use to me.

I'm using Emacs `25.0.50.1` on Debian unstable.

**Comment by purcell** [comment]
I think you can do that just with `ibuffer` -- check out `ibuffer-never-show-predicates` and friends. :-)

**Comment by manuel-uberti** [comment]
Works like a charm. Thank you.
